models:
  claude_code_sdk:
    model: sonnet
    max_turns: 50
    allowed_tools:
    - Read
    - Write
    - Edit
    - Bash
    - Glob
    - Grep
    - MultiEdit
    - WebSearch
    - WebFetch
    permission_mode: acceptEdits
    debug:
      max_turns: 50
      model: sonnet
    sink: # No longer used, goes directly to claude 
      provider: anthropic
      model: claude-opus-4-1-20250805
      fallback: gpt-4o
      bypass_litellm: false
    source: # No longer used, goes directly to claude 
      provider: anthropic
      model: claude-opus-4-1-20250805
      fallback: gpt-4o
      bypass_litellm: false
  schema_analysis:
    sink:
      provider: anthropic
      model: claude-3-5-haiku-latest
      bypass_litellm: false
    source:
      provider: anthropic
      model: claude-3-5-haiku-latest
      bypass_litellm: false
  template_matching:
    provider: anthropic
  code_analysis:
    diagnose:
      provider: anthropic
      model: claude-3-5-haiku-latest
      bypass_litellm: false
    model: claude-3-5-haiku-latest
    bypass_litellm: false
  debugging:
    provider: anthropic
    model: claude-3-5-haiku-latest
    fallback: claude-3-5-haiku-latest
    bypass_litellm: false
  env_var_translation:
    provider: anthropic
    model: claude-3-5-haiku-latest
    bypass_litellm: false
  tech_preparation:
    provider: anthropic
    model: claude-3-5-haiku-latest
    bypass_litellm: false
  app_name_suggestion:
    provider: anthropic
    model: claude-3-5-haiku-latest
    bypass_litellm: false
  log_analysis:
    provider: anthropic
    model: claude-sonnet-4-0
    fallback: claude-sonnet-4-0
    bypass_litellm: false
parameters:
  temperature:
    code_generation: 0.1
    schema_analysis: 0.3
    template_matching: 0.2
    debugging: 0.3
    tech_preparation: 0.5
    app_name_suggestion: 0.7
  max_tokens:
    code_generation: 8000
    schema_analysis: 4000
    template_matching: 2000
    debugging: 4000
  timeout:
    default: 120
    code_generation: 180
    debugging: 240
